[package]
name = "private-key-gen-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0", features = ["derive"] }
ring = "0.16.20"
hex = "0.4"
chrono = "0.4.38"